import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../theme.dart';

/// The decoded contents of an ambulance setup QR generated by the web console:
/// `{ "v": 1, "url": <server>, "id": <login_id>, "pw": <password> }`. The
/// server address is ignored — this app always uses its baked-in backend;
/// only the login ID and password are used.
class SetupPayload {
  SetupPayload({required this.loginId, required this.password});

  final String loginId;
  final String password;

  /// Parses a scanned QR string, returning null if it isn't a valid setup code.
  static SetupPayload? tryParse(String? raw) {
    if (raw == null || raw.isEmpty) return null;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is! Map) return null;
      final id = (decoded['id'] as String?)?.trim() ?? '';
      final pw = (decoded['pw'] as String?) ?? '';
      if (id.isEmpty || pw.isEmpty) return null;
      return SetupPayload(loginId: id, password: pw);
    } catch (_) {
      return null;
    }
  }
}

/// Full-screen camera that reads the ambulance setup QR and pops the parsed
/// [SetupPayload] back to the sign-in screen.
class ScanScreen extends StatefulWidget {
  const ScanScreen({super.key});

  @override
  State<ScanScreen> createState() => _ScanScreenState();
}

class _ScanScreenState extends State<ScanScreen> {
  final _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
    formats: const [BarcodeFormat.qrCode],
  );
  bool _handled = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _onDetect(BarcodeCapture capture) {
    if (_handled) return;
    for (final barcode in capture.barcodes) {
      final payload = SetupPayload.tryParse(barcode.rawValue);
      if (payload != null) {
        _handled = true;
        Navigator.of(context).pop(payload);
        return;
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Scan setup code')),
      body: Stack(
        alignment: Alignment.center,
        children: [
          MobileScanner(controller: _controller, onDetect: _onDetect),
          Container(
            width: 240,
            height: 240,
            decoration: BoxDecoration(
              border: Border.all(color: AppColors.primary, width: 3),
              borderRadius: BorderRadius.circular(kRadiusXl),
            ),
          ),
          Positioned(
            bottom: 48,
            left: 24,
            right: 24,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              decoration: BoxDecoration(
                color: AppColors.foreground.withValues(alpha: 0.85),
                borderRadius: BorderRadius.circular(kRadius),
              ),
              child: const Text(
                'Point at the setup QR from the hospital console',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.white, fontWeight: FontWeight.w500),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
